---
- name: Apply the homeserver.yaml template
  template:
    src: templates/homeserver.yaml.j2
    dest: /etc/matrix-synapse/homeserver.yaml
    owner: root
    group: root
    mode: '0644'

- name: Apply the nginx.conf template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/matrix
    owner: root
    group: root
    mode: '0644'

- name: Enable the nginx site
  file:
    src: /etc/nginx/sites-available/matrix
    dest: /etc/nginx/sites-enabled/matrix
    state: link

- name: Remove the default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

- name: Ensure Synapse is running
  service:
    name: matrix-synapse
    state: started
    enabled: yes
  notify: Restart Synapse